import XCTest
import AVFoundation
import CoreGraphics
import CryptoKit
import LiftingCore
@testable import PowerliftingApp

/// Generated bytes only. Writer-contract fixtures below deliberately do not
/// decode a movie; the model lifecycle method uses an actual generated movie.
final class AnnotationExportTests: XCTestCase {
    func testPortablePackagePreservesBytesRecoveryAndPickerLease() async throws {
        let root = try temporaryRoot(); defer { try? FileManager.default.removeItem(at: root) }
        let exports = root.appendingPathComponent("exports"), media = try generatedBytes(root)
        let store = AnnotationExportStore(rootDirectory: exports, capacity: { _ in 400 * 1024 * 1024 })
        let work = try await store.begin(mediaURL: media), context = self.context(work)
        try await capture(work, context: context)
        let names = [context.localPath, "frames/frame-000000.png", "ledger.json", "prediction.json", "bundle.json"]
        var originals: [String: Data] = [:]
        for name in names { originals[name] = try Data(contentsOf: name == context.localPath ? media : work.capture.appendingPathComponent(name)) }
        let package = try await store.finish(work, context: context, authorization: BarCaptureAuthorization())
        for name in names { XCTAssertEqual(try Data(contentsOf: package.directory.appendingPathComponent(name)), originals[name], name) }
        XCTAssertFalse(FileManager.default.fileExists(atPath: work.directory.path))
        XCTAssertEqual(package.sourceBytes, originals[context.localPath]?.count)
        XCTAssertLessThanOrEqual(package.packageBytes, AnnotationExportStore.packageLimit)
        let receipt = try object(package.directory.appendingPathComponent("export-receipt.json"))
        XCTAssertEqual(receipt["sourceSHA256"] as? String, digest(try XCTUnwrap(originals[context.localPath])))
        let restarted = AnnotationExportStore(rootDirectory: exports, capacity: { _ in Int64.max })
        let recovered = try await restarted.recover()
        XCTAssertEqual(recovered?.id, package.id); XCTAssertEqual(recovered?.packageBytes, package.packageBytes)
        let lease = try await store.acquirePickerLease(package.id)
        XCTAssertEqual(lease.directory, package.directory)
        do { _ = try await store.begin(mediaURL: media); XCTFail("Prepared package did not reserve the single export slot") }
        catch AnnotationExportError.busy {} catch { XCTFail("Unexpected busy refusal: \(error)") }
        let abandoned = exports.appendingPathComponent(".annotation-work-" + UUID().uuidString)
        try FileManager.default.createDirectory(at: abandoned, withIntermediateDirectories: false)
        let unrelated = exports.appendingPathComponent("unrelated.txt")
        try Data("Keep unrelated file".utf8).write(to: unrelated)
        do { try await store.discard(package.id); XCTFail("Deleted a leased package") }
        catch AnnotationExportError.leased {} catch { XCTFail("Unexpected lease refusal: \(error)") }
        XCTAssertTrue(FileManager.default.fileExists(atPath: abandoned.path), "Lease refusal must not start cleanup")
        // This is an ordinary local copy, not a claimed Files-provider UI test.
        let saved = root.appendingPathComponent("user-destination")
        try FileManager.default.copyItem(at: package.directory, to: saved)
        try FileManager.default.removeItem(at: media)
        XCTAssertEqual(try Data(contentsOf: saved.appendingPathComponent(context.localPath)), originals[context.localPath])
        await store.releasePickerLease(package.id)
        try await store.discard(package.id)
        XCTAssertFalse(FileManager.default.fileExists(atPath: package.directory.path))
        XCTAssertFalse(FileManager.default.fileExists(atPath: abandoned.path))
        XCTAssertEqual(try String(contentsOf: unrelated, encoding: .utf8), "Keep unrelated file")
        XCTAssertEqual(try Data(contentsOf: saved.appendingPathComponent("ledger.json")), originals["ledger.json"])
    }

    func testMutationsExtraFilesSymlinksRevocationAndExistingDestinationRefusePublication() async throws {
        let root = try temporaryRoot(); defer { try? FileManager.default.removeItem(at: root) }
        for scenario in ["source", "png", "prediction", "bundle", "extra", "symlink", "revoked", "existing", "staging"] {
            let caseRoot = root.appendingPathComponent(scenario)
            try FileManager.default.createDirectory(at: caseRoot, withIntermediateDirectories: false)
            let media = try generatedBytes(caseRoot), exports = caseRoot.appendingPathComponent("exports")
            let store = AnnotationExportStore(rootDirectory: exports, capacity: { _ in Int64.max })
            let work = try await store.begin(mediaURL: media), context = self.context(work)
            try await capture(work, context: context)
            let original = try Data(contentsOf: media), permission = BarCaptureAuthorization()
            let destination = exports.appendingPathComponent("annotation-" + work.id.uuidString)
            switch scenario {
            case "source": try Data(repeating: 8, count: original.count).write(to: media)
            case "png": try Data("Changed image".utf8).write(to: work.capture.appendingPathComponent("frames/frame-000000.png"))
            case "prediction": try Data("{}".utf8).write(to: work.capture.appendingPathComponent("prediction.json"))
            case "bundle": try Data("{}".utf8).write(to: work.capture.appendingPathComponent("bundle.json"))
            case "extra": try Data("Extra".utf8).write(to: work.capture.appendingPathComponent("extra.txt"))
            case "symlink":
                let image = work.capture.appendingPathComponent("frames/frame-000000.png")
                let outside = caseRoot.appendingPathComponent("outside.png")
                try FileManager.default.copyItem(at: image, to: outside)
                try FileManager.default.removeItem(at: image)
                try FileManager.default.createSymbolicLink(at: image, withDestinationURL: outside)
            case "revoked": permission.invalidate()
            case "existing":
                try FileManager.default.createDirectory(at: destination, withIntermediateDirectories: false)
                try Data("User sentinel".utf8).write(to: destination.appendingPathComponent("keep.txt"))
            case "staging": try Data("Blocking owned staging name".utf8).write(to: work.directory.appendingPathComponent("package"))
            default: XCTFail("Unknown scenario")
            }
            do { _ = try await store.finish(work, context: context, authorization: permission); XCTFail("Invalid \(scenario) package published") }
            catch {}
            if scenario == "existing" {
                XCTAssertEqual(try String(contentsOf: destination.appendingPathComponent("keep.txt"), encoding: .utf8), "User sentinel")
            } else { XCTAssertFalse(FileManager.default.fileExists(atPath: destination.path), scenario) }
            try await store.abort(work)
            XCTAssertFalse(FileManager.default.fileExists(atPath: work.directory.path), scenario)
            XCTAssertTrue(FileManager.default.fileExists(atPath: media.path), scenario)
            if scenario != "source" { XCTAssertEqual(try Data(contentsOf: media), original, scenario) }
        }
    }

    func testSpacePreflightCopyRevocationAndPreparedMutationKeepSource() async throws {
        let root = try temporaryRoot(); defer { try? FileManager.default.removeItem(at: root) }
        let media = try generatedBytes(root), original = try Data(contentsOf: media)
        let noSpace = AnnotationExportStore(rootDirectory: root.appendingPathComponent("no-space"), capacity: { _ in 0 })
        do { _ = try await noSpace.begin(mediaURL: media); XCTFail("Low space accepted") }
        catch AnnotationExportError.space {} catch { XCTFail("Unexpected space error: \(error)") }
        XCTAssertEqual(try Data(contentsOf: media), original)
        let gate = AnnotationCopyGate()
        let store = AnnotationExportStore(rootDirectory: root.appendingPathComponent("exports"), capacity: { _ in Int64.max },
            copyChunkObserver: { url, _ in if url.pathExtension == "mov" { gate.pauseIfArmed() } })
        let work = try await store.begin(mediaURL: media), context = self.context(work)
        try await capture(work, context: context)
        let permission = BarCaptureAuthorization(); gate.arm()
        let copying = Task { try await store.finish(work, context: context, authorization: permission) }
        defer { gate.release() }
        try await awaitGate(gate)
        permission.invalidate(); copying.cancel(); gate.release()
        let copyingResult = await copying.result
        switch copyingResult {
        case .success: XCTFail("Revoked copy published")
        case .failure: break
        }
        try await store.abort(work)
        XCTAssertEqual(try Data(contentsOf: media), original)
        let recoveredAfterCancel = try await store.recover(); XCTAssertNil(recoveredAfterCancel)
        let second = try await store.begin(mediaURL: media), secondContext = self.context(second)
        try await capture(second, context: secondContext)
        let package = try await store.finish(second, context: secondContext, authorization: BarCaptureAuthorization())
        try Data("Changed prediction".utf8).write(to: package.directory.appendingPathComponent("prediction.json"))
        do { _ = try await store.acquirePickerLease(package.id); XCTFail("Mutated prepared package leased") } catch {}
        try await store.discard(package.id)
        XCTAssertEqual(try Data(contentsOf: media), original)
        // A sparse oversized source exercises the physical file-size gate without
        // allocating a huge test buffer or copying a real movie.
        let oversized = root.appendingPathComponent(UUID().uuidString + ".mov")
        XCTAssertTrue(FileManager.default.createFile(atPath: oversized.path, contents: nil))
        let handle = try FileHandle(forWritingTo: oversized)
        try handle.truncate(atOffset: UInt64(501 * 1024 * 1024)); try handle.close()
        do { _ = try await store.begin(mediaURL: oversized); XCTFail("Oversized source accepted") } catch {}
    }

    @MainActor
    func testModelJoinedCopyCancellationRemovalAndReplacementPreserveOwnership() async throws {
        let root = try temporaryRoot(); defer { try? FileManager.default.removeItem(at: root) }
        let source = root.appendingPathComponent("generated.mov")
        try await SyntheticMovieWriter.write(to: source, width: 48, height: 64, frameCount: 3, timescale: 30, asymmetric: true)
        let gate = AnnotationCopyGate()
        let exports = AnnotationExportStore(rootDirectory: root.appendingPathComponent("exports"), capacity: { _ in Int64.max },
            copyChunkObserver: { url, _ in if url.pathExtension == "mov" { gate.pauseIfArmed() } })
        let model = VideoModel(store: VideoImportStore(rootDirectory: root.appendingPathComponent("managed")), annotationExports: exports)
        await model.importFile(source).value
        model.seek(0.05); model.setEnd()
        let first = try await model.prepareAnnotationExport(lift: "deadlift", synthetic: true).value
        let priorID = try XCTUnwrap(model.analysisResult?.analysisID)
        let firstLedger = try object(first.directory.appendingPathComponent("ledger.json"))
        let firstClip = try XCTUnwrap(firstLedger["clip"] as? [String: Any])
        XCTAssertEqual(firstClip["synthetic"] as? Bool, true)
        XCTAssertEqual(firstClip["split"] as? String, "development")
        let movieHash = try BarMediaIdentity.hash(try XCTUnwrap(model.video?.url))
        XCTAssertEqual(firstClip["sourceGroup"] as? String, "recording-sha256-" + movieHash)
        await model.discardAnnotationExport()
        for scenario in ["cancel", "remove", "replace"] {
            if model.video == nil {
                await model.importFile(source).value; model.seek(0.05); model.setEnd()
            }
            let managed = try XCTUnwrap(model.video?.url)
            gate.arm()
            let task = model.prepareAnnotationExport(lift: "deadlift", synthetic: true)
            defer { gate.release() }
            try await awaitGate(gate)
            if scenario == "cancel" {
                model.cancelProcessing(); gate.release()
                let cancelledResult = await task.result
                switch cancelledResult {
                case .success: XCTFail("Cancelled export published")
                case .failure: break
                }
                XCTAssertEqual(model.analysisResult?.analysisID, priorID)
                XCTAssertTrue(FileManager.default.fileExists(atPath: managed.path))
            } else if scenario == "remove" {
                var removalStarted = false
                let removing = Task { @MainActor in removalStarted = true; await model.removeVideo() }
                while !removalStarted { await Task.yield() }
                XCTAssertTrue(FileManager.default.fileExists(atPath: managed.path), "Deleted source before joined copy returned")
                gate.release(); await removing.value
                XCTAssertNil(model.video); XCTAssertFalse(FileManager.default.fileExists(atPath: managed.path))
            } else {
                let replacement = model.importFile(source)
                XCTAssertTrue(FileManager.default.fileExists(atPath: managed.path))
                gate.release(); await replacement.value
                XCTAssertNotEqual(model.video?.url, managed)
                XCTAssertFalse(FileManager.default.fileExists(atPath: managed.path))
            }
            let finalResult = await task.result
            switch finalResult {
            case .success: XCTFail("Stale \(scenario) export published")
            case .failure: break
            }
            XCTAssertNil(model.preparedAnnotationExport)
            XCTAssertFalse(model.processing)
            XCTAssertTrue(FileManager.default.fileExists(atPath: source.path))
        }
        // The Files lease owns completed bytes independently of managed-source
        // removal. Cancellation retains them for retry, then explicit discard
        // removes only preparation, preserving an already saved destination.
        let final = try await model.prepareAnnotationExport(lift: "deadlift", synthetic: true).value
        let leased = try await model.beginSavingAnnotationExport()
        let managed = try XCTUnwrap(model.video?.url)
        let movieName = managed.lastPathComponent, movie = try Data(contentsOf: managed)
        let saved = root.appendingPathComponent("saved-model-export")
        try FileManager.default.copyItem(at: leased.directory, to: saved)
        await model.removeVideo()
        XCTAssertFalse(FileManager.default.fileExists(atPath: managed.path))
        XCTAssertEqual(try Data(contentsOf: final.directory.appendingPathComponent(movieName)), movie)
        await model.discardAnnotationExport()
        XCTAssertEqual(model.preparedAnnotationExport?.id, final.id)
        XCTAssertTrue(model.savingAnnotationExport)
        await model.finishSavingAnnotationExport(final.id, saved: false)
        XCTAssertEqual(model.preparedAnnotationExport?.id, final.id)
        await model.discardAnnotationExport()
        XCTAssertNil(model.preparedAnnotationExport)
        XCTAssertEqual(try Data(contentsOf: saved.appendingPathComponent(movieName)), movie)
    }

    private func context(_ work: AnnotationExportWork) -> BarFrameBundleContext {
        BarFrameBundleContext(prediction: BarPredictionContext(clipID: "generated-portable-" + work.id.uuidString,
            expectedSHA256: work.sourceSHA256, modelID: "generated-portable-test", synthetic: true),
            assetRoot: work.mediaURL.deletingLastPathComponent(), localPath: work.mediaURL.lastPathComponent,
            sourceGroup: "recording-sha256-" + work.sourceSHA256, split: "development",
            permissionEvidence: "Generated contract fixture", lift: "synthetic", targetID: "near-side-hub")
    }
    private func capture(_ work: AnnotationExportWork, context: BarFrameBundleContext) async throws {
        let writer = try BarFrameBundleExporter(mediaURL: work.mediaURL, context: context, destination: work.capture)
        let sink = try await writer.prepare(), run = UUID(), timestamp = BarFrameTime(value: "0", timescale: 30, epoch: 0)
        let raster = try XCTUnwrap(CGContext(data: nil, width: 32, height: 24, bitsPerComponent: 8, bytesPerRow: 128,
            space: CGColorSpaceCreateDeviceRGB(), bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue))
        raster.setFillColor(CGColor(red: 0.2, green: 0.5, blue: 0.9, alpha: 1)); raster.fill(CGRect(x: 0, y: 0, width: 32, height: 24))
        let png = try BarFramePNG.encode(XCTUnwrap(raster.makeImage()))
        try await sink.receive(BarCapturedFrame(sessionID: sink.sessionID, analysisID: run, timestamp: timestamp, width: 32, height: 24, png: png))
        let sample = try VideoTraceSample(seconds: 0, point: nil, confidence: 0, kind: .lost)
        _ = try await writer.finish(result: BarAnalysisResult(trace: try VideoTrace(start: 0, end: 0.1, samples: [sample]),
            timestamps: [timestamp], elapsed: 0.1, gaps: 1, mode: .automatic, uprightWidth: 32, uprightHeight: 24,
            analysisID: run, captureSessionID: sink.sessionID))
    }
    private func generatedBytes(_ root: URL) throws -> URL {
        let url = root.appendingPathComponent(UUID().uuidString + ".mov")
        try Data(repeating: 37, count: 256 * 1024).write(to: url)
        return url
    }
    private func temporaryRoot() throws -> URL {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: false); return root
    }
    private func object(_ url: URL) throws -> [String: Any] { try XCTUnwrap(JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any]) }
    private func digest(_ bytes: Data) -> String { SHA256.hash(data: bytes).map { String(format: "%02x", Int($0)) }.joined() }
    private func awaitGate(_ gate: AnnotationCopyGate) async throws {
        let deadline = ProcessInfo.processInfo.systemUptime + 45
        while !gate.entered {
            guard ProcessInfo.processInfo.systemUptime < deadline else { throw AnnotationExportError.budget }
            try await Task.sleep(nanoseconds: 10_000_000)
        }
    }
}

private final class AnnotationCopyGate: @unchecked Sendable {
    private let lock = NSCondition()
    private var armed = false, didEnter = false, released = false
    var entered: Bool { lock.lock(); defer { lock.unlock() }; return didEnter }
    func arm() { lock.lock(); armed = true; didEnter = false; released = false; lock.unlock() }
    func pauseIfArmed() {
        lock.lock()
        guard armed else { lock.unlock(); return }
        armed = false; didEnter = true
        let deadline = Date().addingTimeInterval(5)
        while !released { if !lock.wait(until: deadline) { break } }
        lock.unlock()
    }
    func release() { lock.lock(); released = true; lock.broadcast(); lock.unlock() }
}
